# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d88ee029dde291b1a0a7ffeef41f0ea1c3fcd39d962bcc216f3c6924806fda28b5aaf94463c8917a040471863bfdedbe38ba8d32106b07967a41e396e300932e

test:
  secret_key_base: f6c4cbae9f9e532bc5a9e95cdec33d758a4fa17f4196b5cc18eae07e0fa9457dcde75909fbc49fdc814a98a5b4b385e87d3cd8f483145c172d6e2979057f72ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
